apiVersion: cert-manager.io/v1alpha2 
# certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letscencrypt.org/directory
        email: 'info@agentscovetech.com'
        privateKeySecretRef:
            name: letscencrypt-prod 
        solvers:
            - http01: 
                ingress:
                    class: nginx
